export const Users = [
    {
        id: 1,
        profilePicture: 'blacka.jpeg',
        username: 'Hồ Ân',
    },
    {
        id: 2,
        profilePicture: 'blackpink.jpg',
        username: 'Blackpink',
    },
    {
        id: 3,
        profilePicture: 'bray.jpeg',
        username: 'Bao Thanh Thiên',
    },
    {
        id: 4,
        profilePicture: 'dad.jpg',
        username: 'Xuân Đức Lê',
    },
    {
        id: 5,
        profilePicture: 'mom.jpg',
        username: 'Kim Dung Trần',
    },
    {
        id: 6,
        profilePicture: 'phuc.jpg',
        username: 'Xuân Phúc',
    },
    {
        id: 7,
        profilePicture: 'family.jpg',
        username: 'Nhà Lộc',
    },
    {
        id: 8,
        profilePicture: 'Lisa.jpeg',
        username: 'Lalisa',
    },
    {
        id: 9,
        profilePicture: 'pewpew.jpg',
        username: 'Pew pew',
    },
    {
        id: 10,
        profilePicture: 'van.jpg',
        username: 'Vân Nguyễn',
    },
];

export const Posts = [
    {
        id: 1,
        desc: 'Love For All, Hatred For None.',
        photo: 'Jenny1.jpeg',
        date: '5 mins ago',
        userId: 1,
        like: 32,
        comment: 9,
    },
    {
        id: 2,
        photo: 'Jsoo1.jpeg',
        date: '15 mins ago',
        userId: 2,
        like: 2,
        comment: 1,
    },
    {
        id: 3,
        desc: 'Every moment is a fresh beginning.',
        photo: 'mixi.jpeg',
        date: '1 hour ago',
        userId: 3,
        like: 61,
        comment: 2,
    },
    {
        id: 4,
        photo: 'lowg.jpeg',
        date: '4 hours ago',
        userId: 4,
        like: 7,
        comment: 3,
    },
    {
        id: 5,
        photo: 'Jsoo1.jpeg',
        date: '5 hours ago',
        userId: 5,
        like: 23,
        comment: 5,
    },
    {
        id: 6,
        photo: 'naruto.jpeg',
        date: '1 day ago',
        userId: 6,
        like: 44,
        comment: 6,
    },
    {
        id: 7,
        desc: 'Never regret anything that made you smile.',
        photo: 'sasuke.jpeg',
        date: '2 days ago',
        userId: 7,
        like: 52,
        comment: 3,
    },
    {
        id: 8,
        photo: 'family1.jpg',
        date: '3 days ago',
        userId: 8,
        like: 15,
        comment: 1,
    },
    {
        id: 9,
        desc: 'Change the world by being yourself.',
        photo: 'viruss.jpeg',
        date: '5 days ago',
        userId: 9,
        like: 11,
        comment: 2,
    },
    {
        id: 10,
        photo: 'sontung.jpeg',
        date: '1 week ago',
        userId: 10,
        like: 104,
        comment: 12,
    },
];
